config/routes.rb
Rails.application.routes.draw do
  root 'products#index'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resource :cart, only: :show
  resources :sessions, only: [:new, :create, :destroy]
  resources :order_items, only: [:create, :update, :destroy]
  resources :products, :users
  resources :categories, :photos, only: [:create, :update, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  validates :name, presence: true, length: { maximum: 50 }
end

app/models/current_order.rb
class CurrentOrder < ApplicationRecord
  belongs_to :user
  belongs_to :order
  validates :user, presence: true
  validates :order, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  validates :user, presence: true
  has_many :order_items, dependent: :destroy
  validates  :status,
    presence: true, 
    inclusion: { in: ['IN_PROGRESS', 'ORDERED', 'FULFILLED', 'CANCELLED'] }
  # date_placed
  # date_fulfilled
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  validates :order, presence: true
  belongs_to :product
  validates :product, presence: true
  validates :quantity,
    presence: true,
    numericality: { only_integer: true, greater_than: 0 } 
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :product
  validates :product, presence: true
  validates :description, length: { maximum: 255 }
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  validates :category, presence: true
  validates :name, presence: true, length: { maximum: 50 }
  validates :price, presence: true
  validates :description, length: { maximum: 1000 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders
  has_one :current_order # solely used for finding cart
  has_one :cart, through: :current_order, source: :order
  validates :email,
    presence: true,
    uniqueness: { case_sensitive: false },
    format: { with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i },
    length: { maximum: 255 }
  has_secure_password
  validates :password,
    presence: true,
    length: { minimum: 8 },
    allow_nil: true
  validates :admin, inclusion: { in: [true, false] }
  attr_accessor :remember_token

  class << self
    def create_hash(string)
      BCrypt::Password.create(string)
    end

    def generate_token
      SecureRandom.urlsafe_base64
    end
  end

  def remember
    self.remember_token = User.generate_token
    update_attribute(:remember_digest, User.create_hash(remember_token))
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def authenticated?(attribute, token)
    digest = self["#{attribute}_digest"] # to symbol? send?
    # digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  private

  def require_login
    unless logged_in?
      store_location
      flash[:error] = "You must log in first."
      redirect_to login_url
    end
  end

  def require_admin
    unless current_user.admin?
      flash[:error] = "You must be an admin to do that."
      redirect_to root_url
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :require_login
  def show
    @cart = current_user.cart
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def create
  end

  def destroy
  end

  def update
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  before_action :require_login
  
  def create
    product = Product.find(params[:order_item][:product_id])
    order_items = OrderItem.where(order: current_user.cart, product: product)
    if order_item = order_items.first
      order_item.quantity += params[:order_item][:quantity].to_i
    else
      order_item = OrderItem.new(order_item_params)
      order_item.order = current_user.cart
    end
    order_item.save
    flash[:success] = 'Product successfully added to cart'
    redirect_to product
  end

  def update
  end

  def destroy
    OrderItem.find(params[:id]).destroy
    flash[:success] = 'Item successfully removed from cart'
    redirect_to cart_path
  end

  private

  def order_item_params
    params.require(:order_item).permit(:product_id, :quantity)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :require_admin, only: [:new, :create, :edit, :update, :destroy]
  
  def show
    @product = Product.find(params[:id])
  end

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:success] = 'Product successfully created.'
      redirect_to products_path
    else
      render new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
  end

  def destroy
    Product.find(params[:id]).destroy
    flash[:success] = 'Product successfully deleted.'
    redirect_to products_path
  end

  private

  def product_params
    params.require(:product).permit(:name, :price, :description, :category_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      log_in @user
      params[:session][:remember_me] == '1' ? remember(@user) : forget(@user)
      return_or_redirect_to root_url
    else
      flash.now[:danger] = "Email or password is incorrect"
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.admin = false
    order = Order.new(user: @user, status: 'IN_PROGRESS')
    cart = CurrentOrder.new(user: @user, order: order)
    if @user.save
      order.save
      cart.save
      log_in @user
      flash[:success] = 'Account successfully created.'
      redirect_to root_url
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    elsif cookies.signed[:user_id]
      user = User.find_by(id: cookies.signed[:user_id])
      if user && user.authenticated?(:remember, cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  # check if a given user is the current logged in user
  def current_user?(user)
    user == current_user
  end

  def logged_in?
    !current_user.nil?
  end

  # Redirects to stored location (or to the default).
  def return_or_redirect_to(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/show.html.erb
<h1>Your Cart</h1>
<% if @cart.order_items.count > 0 %>
  <ul>
    <%= render @cart.order_items %>
  </ul>
<% else %>
  <p>Your cart is empty.</p>
<% end %>

app/views/order_items/_order_item.html.erb
<li>
  <%= link_to order_item.product.name, order_item.product %>
  <%= order_item.product.price %>
  <%= order_item.quantity %>
  <% if order_item.order.user == current_user %>
    <%= button_to 'Remove', order_item, { method: :delete, form_class: "delete-button" } %>
  <% end %>
</li>

app/views/products/_product.html.erb
<li>
  <%= link_to product.name, product %>
  <%= button_to 'Delete', product, { method: :delete, form_class: "delete-button" } %>
</li>

app/views/products/edit.html.erb
<h1>Products#edit</h1>
<p>Find me in app/views/products/edit.html.erb</p>

app/views/products/index.html.erb
<h1>Products</h1>

<ul>
  <%= render @products %>
</ul>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>
<%= form_for @product, url: { action: "create" } do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  
  <%= f.label :name %>
  <%= f.text_field :name %>
  
  <%= f.label :price %>
  <%= f.number_field :price %>
  
  <%= f.label :description %>
  <%= f.text_area :description %>
  
  <%= f.label :category %>
  <%= f.collection_select :category_id, Category.all, :id, :name, prompt: true %>

  <button type="button">Add Photo</button>

  <%= f.submit "Create Product" %>
<% end %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>
<p><b>Price: </b><%= number_to_currency(@product.price.to_f / 100) %></p>
<p><b>Category: </b><%= @product.category.name %></p>
<p><b>Description: </b><%= @product.description %></p>
<%= form_for(OrderItem.new) do |f| %>
  <%= f.hidden_field :product_id, value: @product.id %>
  
  <%= f.label :quantity %>
  <%= f.number_field :quantity, value: 1 %>

  <%= f.submit "Add To Cart" %>
<% end %>
<%= link_to 'All Products', products_path %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :confirm_password, "Confirm Password" %>
  <%= f.password_field :confirm_password %>

  <%= f.submit "Create Account" %>
<% end %>